name: deploy-frontend
on:
  push:
    branches:
      - main
    paths:
      - 'src/apps/CryptoWars/frontend/**'
      - '.github/workflows/deploy-frontend.yml'

defaults:
  run:
    working-directory: src/apps/CryptoWars/frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/latest
      - run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}} --paths "/latest/index.html"
